name: Generar APK de Kotlin

on:
  workflow_dispatch: # Esto activa el botón manual para compilar cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Compilar APK con Gradle
        run: ./gradlew assembleDebug

      - name: Subir APK final a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
